### ISSUE TITLE
on_update_chat_is_pinned fails

### ISSUE THREAD

**Issue by marhkb** [fewensa/telegram-client#16]
When I listen to `on_update_chat_is_pinned` and pin or unpin a chat from the telegram App I get this error in my application.
```
ERROR telegram_client::handler   > TELEGRAM DATA FAIL. IF YOU SEE THIS MESSAGE, PLEASE POST AN ISSUE TO https://github.com/fewensa/telegram-client/issues 
 INCLUDE THIS JSON => {"@type":"updateChatIsPinned","chat_id":92719471,"is_pinned":false,"order":"6855196828699253162"}
```

PS: Thanks for this nice library

EDIT:
rtdlib = "1.6.2"
telegram-client = "1.6.1"
libtd: 1.6.0

**Comment by fewensa** [comment]
Thanks for report this issue. Yes. I know that. It's a bug, but not rtdlib bugs.

You can see that:

https://github.com/fewensa/fantasy/blob/6e8bba1637ca2ce7aac09430c3c98f9132bec30f/schema/v1.6.0/td_api.tl#L2780-L2781

```text
//@description A chat was pinned or unpinned @chat_id Chat identifier @is_pinned New value of is_pinned @order New value of the chat order
updateChatIsPinned chat_id:int53 is_pinned:Bool order:int64 = Update;
```

In tdlib tl file, The `updateChatIsPinned`'s order type is int64, but the tdlib returned data is string

```json
{"@type":"updateChatIsPinned","chat_id":92719471,"is_pinned":false,"order":"6855196828699253162"}
```

and then, the `serde_json` project can't deserialize that. now, a common practice in tdlib is that if  encounter this problem, I will change the data type to String.

https://github.com/fewensa/fantasy/blob/6e8bba1637ca2ce7aac09430c3c98f9132bec30f/schema/td_type_fill.toml#L18-L93


It has not included all error types, so you encountered this error.

But, @jclulow post an [issue](https://github.com/fewensa/fantasy/issues/1) seems to solve the problem, However, I have not submitted pr to me. 

So recently I will release a new version to fix this bug, and the best way is @jclulow create a pr to fix that.

**Comment by jclulow** [comment]
Sorry I've been meaning to get back to that!  Just been busy.

**Comment by fewensa** [comment]
> 
> 
> Sorry I've been meaning to get back to that! Just been busy.

Thanks for your help, and you can modify it when you have time 😄

**Comment by marhkb** [comment]
Thanks for the explanation. When I first looked at 'Chat' struct I indeed was wondering why 'order' was a String there. 
However, there are still some 'order' fields in other structs not encoded as String but as isize.
These are in 
1. UpdateChatDraftMessage
2. UpdateChatIsPinned (the reason for this bug report)
3. UpdateChatIsSponsored 
4. UpdateChatOrder

As I am currently building an gtk telegram client I am encountering issues with the order of chats the further I progress.
Could you also change those in the meantime until the solution of @jclulow is finished?

**Comment by fewensa** [comment]
Thanks for your report those struct, If you found more struct as same questions, now you can reply this issue before Aug 10, In the Aug 10 I will fix it and publish a new version.
Until jclulow is not released, it may be necessary to release a temporary version to solve this problem, or jclulow has not been released for a long time, I will fix this problem myself.

-------- Original Message --------
On Aug 8, 2020, 21:23, marhkb < notifications@github.com> wrote:
Thanks for the explanation. When I first looked at 'Chat' struct I indeed was wondering why 'order' was a String there.
However, there are still some 'order' fields in other structs not encoded as String but as isize.
These are in
UpdateChatDraftMessage
UpdateChatIsPinned (the reason for this bug report)
UpdateChatIsSponsored
UpdateChatOrder
As I am currently building an gtk telegram client I am encountering issues with the order of chats the further I progress.
Could you also change those in the meantime until the solution of @jclulow is finished?
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.￼
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/fewensa/telegram-client/issues/16#issuecomment-670928685">https://github.com/fewensa/telegram-client/issues/16#issuecomment-670928685", "url": "[https://github.com](<a href=)/fewensa/telegram-client/issues/16#issuecomment-670928685">https://github.com/fewensa/telegram-client/issues/16#issuecomment-670928685", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by fewensa** [comment]
> 
> 
> Thanks for the explanation. When I first looked at 'Chat' struct I indeed was wondering why 'order' was a String there.
> However, there are still some 'order' fields in other structs not encoded as String but as isize.
> These are in
> 
>     1. UpdateChatDraftMessage
> 
>     2. UpdateChatIsPinned (the reason for this bug report)
> 
>     3. UpdateChatIsSponsored
> 
>     4. UpdateChatOrder
> 
> 
> As I am currently building an gtk telegram client I am encountering issues with the order of chats the further I progress.
> Could you also change those in the meantime until the solution of @jclulow is finished?

Hi, I publish a new version([rtdlib@1.6.3](https://crates.io/crates/rtdlib/1.6.3)) to crates.io. You need remove your project `Cargo.lock` file, and recompile, the `telegram-client` will automatically depend on the latest version.
Now only 1.6.3+ version do these change. 

There are two things you need to known:

1. Currently changing the order type to String is only a temporary solution, and it will be changed to a number(isize) in the future
2. When I change `order` type, I follow the master branch [td](https://github.com/tdlib/td), now, the last td remove some structs includes `UpdateChatIsPinned` `UpdateChatIsSponsored` `UpdateChatOrder`, and  the `UpdateChatDraftMessage` not have `order` field, It's changed to `ChatPosition` struct. If you use 1.6.* will not affect


If you found more struct have same question, You can tell me here. Before this problem is completely solved, I will fix the wrong type within 2 days. Or you can clone [fantasy](https://github.com/fewensa/fantasy) to your local, and run it. change 

https://github.com/fewensa/fantasy/blob/fa9027e4bfe7a1591bdda234f3d14e6a3fe1b227/fantasy/src/main.rs#L43

```
.file_tl(project_path.join("schema/master/td_api.tl"))  //     "schema/v1.6.0/td_api.tl"
```

And then add filter type in td_type_fill.toml

https://github.com/fewensa/fantasy/blob/fa9027e4bfe7a1591bdda234f3d14e6a3fe1b227/schema/td_type_fill.toml#L16-L143


When you run it project, will generate a new rtdlib project, Some missing files(like Cargo.toml), just add them

**Comment by fewensa** [comment]
Hi @marhkb , the new version of telegram-client and rtdlib published, and change type to isize, Solution using @jclulow

**Comment by marhkb** [comment]
Thx @fewensa. New version is working fine here.
