### ISSUE TITLE
EventApi.send isn't found

### ISSUE THREAD

**Issue by ivnsch** [fewensa/telegram-client#21]
I cloned your repository and ran the "sample" example. The EventApi.send calls doesn't compile:

https://github.com/fewensa/telegram-client/blob/master/examples/sample/main.rs#L78
> method not found in `&EventApi`

It also happens with v1.7.*

**Comment by fewensa** [comment]
Yes, because of the upgrade, this example forgot to modify 

the `send` api is support in this commit
https://github.com/fewensa/telegram-client/blob/dbc46a97c5da27e9ae061de6eab60714e9f98c8f/src/api/api.rs#L30

now use `set_tdlib_parameters` api.
https://github.com/fewensa/telegram-client/blob/3b13d9e59ea35996e69eafa26a49e315877553d0/src/api/aevent.rs#L1436

it fix in next version. or you can try the [full_client](https://github.com/fewensa/telegram-client/blob/3b13d9e59ea35996e69eafa26a49e315877553d0/examples/full_client/main.rs#L18) example

**Comment by fewensa** [comment]
The new version released https://crates.io/crates/telegram-client
