### ISSUE TITLE
full_client blocks unable to complete connection

### ISSUE THREAD

**Issue by Matthias-Fauconneau** [fewensa/telegram-client#9]
[telegram-client.log](https://github.com/fewensa/telegram-client/files/3775918/telegram-client.log)

P.S: It would be nice if log output would not leak credentials (phone number, API id+hash) 
P.S: I don't know what the 'proxy' business is for

**Comment by fewensa** [comment]
Yes, not leak credentials is good. I will improve the log.

About proxy, because my network not access telegram, So I need pass proxy to connect telegram. If you can, you don't need proxy, remove [full_client/main.rs#L29](https://github.com/fewensa/telegram-client/blob/f7f2740b02/examples/full_client/main.rs#L29)  or [conf/telegram-client.toml#L2-L6](https://github.com/fewensa/telegram-client/blob/f7f2740b02/conf/telegram-client.toml#L2). 

The next commit, In full_client example, The proxy configuration will be change to default to no proxy.

In addition, Use last code https://github.com/fewensa/telegram-client/issues/8 , It's important. The previous code is problem and will result in the inability to send the request.
